language: php
php:
  - 5.5
  - 5.6
before_insall: git submodule update --init
script:
  - phpunit test
notifications:
  emails:
    - tadatoshi.tokutake@gmail.com
  on_success: change
  on_failure: always
